version: '3.8'

services:
  backend:
    image: acpcproject:latest
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./app:/run  # Mount your local app directory
      - ./app.db:/app/app.db  # Mount the SQLite database file
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES}
      - JWT_REFRESH_TOKEN_EXPIRES=${JWT_REFRESH_TOKEN_EXPIRES}

  frontend:
    image: acpcprojectfront:latest
    container_name: frontend
    ports:
      - "3000:3000"  # Exposing port 80 in the container as port 3000 on the host

volumes:
  backend-data:
