"""empty message

Revision ID: 14a03a978c63
Revises: fb2912ff8c19
Create Date: 2024-08-16 01:33:24.645552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a03a978c63'
down_revision = 'fb2912ff8c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_name', ['name'], unique=1)

    # ### end Alembic commands ###
