"""Add user table

Revision ID: 081448d7bd1d
Revises: 06af6a776404
Create Date: 2024-08-11 04:40:45.920709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081448d7bd1d'
down_revision = '06af6a776404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
